set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set nomodeline  " disable mode lines (security measure)
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk
set fileformats=unix,dos,mac
set mouse=a
set virtualedit=block

" set spell
" set spellang=en_us
" set dictionary+=~/.config/nvim/dict

set background=dark
colorscheme space_vim_theme
let g:space_vim_transp_bg = 1
" colorscheme deus

" h folding
set foldmethod=indent
set nofoldenable
set foldlevel=99
set foldlevelstart=99
set foldcolumn=0

set hidden

set confirm

set noundofile
" set undolevels=1000
" set undoreload=10000
set nobackup
set noswapfile
silent !mkdir -p ~/.config/nvim/tmp/{undo,swp,backup}
set undodir=~/.config/nvim/tmp/undo//,.
set backupdir=~/.config/nvim/tmp/backup//,.
set directory=~/.config/nvim/tmp/swp//,.

set number
set relativenumber
set textwidth=0
set wrap
set linebreak
set wrapmargin=2
set cursorline
set ruler
set list
set listchars=trail:▫,tab:,extends:≫,precedes:≪
set scrolloff=6
set viewoptions=folds,options,cursor,unix,slash  " Better Unix / Windows compatibility

" open big file for fast
set lazyredraw

" cancel the annoying bell
set visualbell
set noerrorbells

set autoread
set autowrite
" set autowriteall

" indent
set autoindent
set indentexpr=
set backspace=indent,eol,start
set smartindent
" set paste

" search
exec 'nohlsearch'
set incsearch
set ignorecase
set smartcase
set hlsearch

set showmatch
set matchtime=2

" Define how to use the CTRL-A and CTRL-X commands for adding to and subtracting from a number respectively
set nrformats=alpha,octal,hex

" tab
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set formatoptions-=tc

" auto to dir
set laststatus=2
set showcmd
set autochdir
" set noautochdir
set history=1000
" set notimeout
set timeoutlen=1000
set shortmess+=c

" show commend meun
set wildmenu
if has('nvim')
  set wildoptions=pum
  " set termguicolors " 和一个插件冲突
  set pumblend=30
else " for vim
  set wildmode=list:longest,full
endif

set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc,.git\*,.hg\*,.svn\*

" split window behaviors
set splitright
set splitbelow

" ------* set Universal CTags *--------
" ctags -R -f .tags
set tags=./.tags;,.tags


" -------* cscope *--------
" cscope -Rbq
if has("cscope")
  set csprg=/usr/bin/cscope
  set csto=1
  set cst
  set nocsverb
  " add any database in current directory
  if filereadable("cscope.out")
    set noautochdir
    cs add cscope.out
  endif
  set csverb
endif

set cscopequickfix=s-,c-,d-,i-,t-,e-
set switchbuf=useopen


" 打开自动定位到上次编辑的位置
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

if has('nvim')  " for nvim
  set clipboard+=unnamedplus
  set inccommand=split
  set diffopt=vertical,algorithm:histogram,indent-heuristic

else   " for vim
  let g:netrw_liststyle = 3
  let g:netrw_winsize = 30
  autocmd FileType netrw setlocal bufhidden=delete

  syntax enable
  syntax on
  set clipboard=unnamedplus
  set completeopt=menuone,menu,preview,longest

  " ---- gvim ---- "
  set guifont=Source\ Code\ Pro\ 14
  set guioptions-=T
  set guioptions-=r
  set guioptions-=m
endif

"----- auto fcitx  -----
let g:input_toggle = 1
function! Fcitx2en()
   let s:input_status = system("fcitx-remote")
   if s:input_status == 2
      let g:input_toggle = 1
      let l:a = system("fcitx-remote -c")
   endif
endfunction

function! Fcitx2zh()
   let s:input_status = system("fcitx-remote")
   if s:input_status != 2 && g:input_toggle == 1
      let l:a = system("fcitx-remote -o")
      let g:input_toggle = 0
   endif
endfunction

autocmd InsertLeave * call Fcitx2en()
" autocmd InsertEnter * call Fcitx2zh()
"----- auto fcitx end -----
