set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set nomodeline  " disable mode lines (security measure)
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk,utf-16le,cp1252,iso-8859-15,ucs-bom
set fileformats=unix,dos,mac
set mouse=a

set background=dark
" colorscheme gruvbox9
colorscheme space_vim_theme
" let g:gruvbox_transp_bg = 1
let g:space_vim_transp_bg = 1
let &t_ut=''
let t_Co=256

set foldmethod=indent
set nofoldenable
set foldlevel=99
set foldlevelstart=99

set hidden

set confirm

set noundofile
" set undolevels=1000
" set undoreload=10000
set nobackup
set noswapfile
silent !mkdir -p ~/.config/nvim/tmp/{undo,swp,backup}
set undodir=~/.config/nvim/tmp/undo//,.
set backupdir=~/.config/nvim/tmp/backup//,.
set directory=~/.config/nvim/tmp/swp//,.

set number
set relativenumber
set textwidth=0
" set textwidth=80
set wrap
set linebreak
set wrapmargin=2
set cursorline
set ruler
set list
set listchars=trail:▫,tab:,extends:≫,precedes:≪
set scrolloff=6
set viewoptions=folds,options,cursor,unix,slash  " Better Unix / Windows compatibility
" set colorcolumn=+1  " color the 81 column for warning

" open big file for fast
set lazyredraw

" cancel the annoying bell
set visualbell
set noerrorbells
set noerrorbells novisualbell t_vb=
set belloff=all

set autoread
set autowrite
set autowriteall
" set virtualedit=onemore  " used with caution of breaking plugins

" indent
set autoindent
set indentexpr=
set backspace=indent,eol,start
set smartindent
" set paste
" set copyindent

" search
exec 'nohlsearch'
set showmatch
set incsearch
set ignorecase
set smartcase
set hlsearch

" tab
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set formatoptions-=tc
" set smarttab

" auto to dir
set laststatus=2
set showcmd
set autochdir
set history=1000
set timeoutlen=500
set timeout

" show commend meun
set wildmenu
if has('nvim')  " Use floating windows to complete the commond, only neovim support
  set wildoptions=pum
  " set termguicolors " 和一个插件冲突
  set pumblend=30  " Let floatingwindow to be transparable
else " for vim
  set wildmode=list:longest,full
endif

set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc,.git\*,.hg\*,.svn\*

" split window behaviors
set splitright
set splitbelow

" set Universal CTags
set tags=./.tags;,.tags
let gitroot = substitute(system('git rev-parse --show-toplevel'),'[\n\r]', '', 'g') " Make tags placed in .git/tags file available in all levels of a repository
if gitroot != ''
    let &tags = &tags . ',' . gitroot . '/.git/tags'
endif

" set whichwrap=b,s,h,l,<,>,~,[,] " Backspace and cursor keys wrap too
" set iskeyword-=_,.,=,-,:,
" set spell spellang=en_us
" set dictionary+=~/.config/nvim/dict
" display and register show register content

set switchbuf=useopen  " quickfix window instead of opening new buffers

" 打开自动定位到上次编辑的位置
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

if has('nvim')  " for nvim
  " syntax enable
  " syntax on
  set clipboard+=unnamedplus
  set inccommand=split

else   " for vim
  syntax enable
  syntax on
  set clipboard=unnamedplus
  set ttyfast
  set completeopt=menuone,menu,preview,longest

  " ---- gvim ---- "
  set guifont=Source\ Code\ Pro\ 14
  set guioptions-=T
  set guioptions-=r
  set guioptions-=m
endif
