local _Lsp_symbols = {
  Text          = "  (Text) ",
  Method        = "  (Method)",
  Function      = "  (Function)",
  Constructor   = "  (Constructor)",
  Field         = " ﴲ (Field)",
  Variable      = "[](Variable)",
  Class         = "  (Class)",
  Interface     = " ﰮ (Interface)",
  Module        = "  (Module)",
  Property      = " 襁(Property)",
  Unit          = "  (Unit)",
  Value         = "  (Value)",
  Enum          = " 練(Enum)",
  Keyword       = "  (Keyword)",
  Snippet       = " ﬌ (Snippet)",
  Color         = "  (Color)",
  File          = "  (File)",
  Reference     = "  (Reference)",
  Folder        = "  (Folder)",
  EnumMember    = "  (EnumMember)",
  Constant      = " ﲀ (Constant)",
  Struct        = " ﳤ (Struct)",
  Event         = "  (Event)",
  Operator      = "  (Operator)",
  TypeParameter = "  (TypeParameter)",
}

-- local _Lsp_symbols = {
--   Text          = "  ",
--   Method        = "  ",
--   Function      = "  ",
--   Constructor   = "  ",
--   Field         = " ﴲ ",
--   Variable      = "[]",
--   Class         = "  ",
--   Interface     = " ﰮ ",
--   Module        = "  ",
--   Property      = " 襁",
--   Unit          = "  ",
--   Value         = "  ",
--   Enum          = " 練",
--   Keyword       = "  ",
--   Snippet       = " ﬌ ",
--   Color         = "  ",
--   File          = "  ",
--   Reference     = "  ",
--   Folder        = "  ",
--   EnumMember    = "  ",
--   Constant      = " ﲀ ",
--   Struct        = " ﳤ ",
--   Event         = "  ",
--   Operator      = "  ",
--   TypeParameter = "  "
-- }

return _Lsp_symbols
